#User-specific source files
list(APPEND PELEC_EXTRA_SOURCES ${CMAKE_SOURCE_DIR}/Exec/RegTests/DIFF/probdata.f90)
list(APPEND PELEC_EXTRA_SOURCES ${CMAKE_SOURCE_DIR}/Exec/RegTests/DIFF/Prob_nd.F90)
list(APPEND PELEC_EXTRA_SOURCES ${CMAKE_SOURCE_DIR}/Exec/RegTests/DIFF/Problem_Derive_F.H)
list(APPEND PELEC_EXTRA_SOURCES ${CMAKE_SOURCE_DIR}/Exec/RegTests/DIFF/Problem_Derives.H)
list(APPEND PELEC_EXTRA_SOURCES ${CMAKE_SOURCE_DIR}/Exec/RegTests/DIFF/problem_derive_nd.F90)

#Compile-time options for executable
set(PELEC_DIM 3)
set(PELEC_ENABLE_EB OFF)
set(PELEC_ENABLE_MASA OFF)
set(PELEC_ENABLE_REACTIONS OFF)
set(PELEC_ENABLE_MOL OFF)
set(PELEC_ENABLE_PARTICLES OFF)
set(PELEC_EOS_MODEL GammaLaw)
set(PELEC_REACTIONS_MODEL Null)
set(PELEC_TRANSPORT_MODEL Constant)
