PRECISION  = DOUBLE
PROFILE    = FALSE
USE_EB     = FALSE
DEBUG      = FALSE

DIM        = 2

COMP	   = gcc

USE_MPI    = FALSE
USE_OMP    = FALSE

# Include particles (currently spray) capability/sources
USE_PARTICLES = TRUE

#The belos spec is Hacky max. 
SPRAY_COMPONENTS = 8

DEFINES += -DSPRAY_COMPONENTS=$(SPRAY_COMPONENTS)

# define the location of the PELE top directory
PELE_HOME    := ../../..

# This sets the EOS directory in $(PELE_PHYSICS_HOME)/Eos
Eos_dir     := GammaLaw

# This sets the network directory in $(PELE_PHYSICS_HOME)/Reactions
Reactions_dir := Null

# This sets the transport directory in $(PELE_PHYSICS_HOME)/Transport
Transport_dir := Constant

Bpack   := ./Make.package

include ../Make.PeleC

ifeq ($(DEBUG), TRUE)
DEFINES += -DDEBUG
endif

DEFINES += -DBL_USE_EB
