#ifndef PeleC_Parameters_H_
#define PeleC_Parameters_H_

static AMREX_GPU_DEVICE_MANAGED double Ru = 8.31451e07; 
static AMREX_GPU_DEVICE_MANAGED double smallT = 1.0e-50; 
static AMREX_GPU_DEVICE_MANAGED double small = 1.0e-50;
static AMREX_GPU_DEVICE_MANAGED double small_dens = 1.0e-16; 
static AMREX_GPU_DEVICE_MANAGED double small_pres = 1.0e-50; 
static AMREX_GPU_DEVICE_MANAGED double smallu     = 1.0e-16;  
static AMREX_GPU_DEVICE_MANAGED double n_A = 6.02214129e23; 
static AMREX_GPU_DEVICE_MANAGED double k_B = 1.3806488e-16;
 
#endif
