#ifndef PELEC_INDEX_H_
#define PELEC_INDEX_H_

/*Only valid for LiDryer. TODO Make Fuego do this*/


#define URHO      0 
#define UMX       1 
#define UMY       2
#define UMZ       3 
#define UEINT     4
#define UEDEN     5
#define UTEMP     6
#define UFS       7
#define UFX       0 
#define NVAR      16

#define QRHO      0
#define QU        1
#define QV        2 
#define QW        3 
#define QGAME     4
#define QPRES     5
#define QREINT    6
#define QTEMP     7
#define QFS       8 
#define QFX       0
#define QVAR      17

#define QGAMC     0
#define QC        1
#define QCSML     2 
#define QDPDR     3
#define QDPDE     4
#define QRSPEC    5
#define npassive 10 


#endif 
